name: Build and Publish Dockerimage
on:
  workflow_dispatch:
  push:
    branches:  [ master, ci/build-dockerimage ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: anagavrilovic
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfile
          push: true
          tags: anagavrilovic/hospital-gateway:latest